version: "3"
services:
  backend:
    image: snookers-sells-be
    build: ../test-application-be
    environment:
      SS_DB_HOST: db:5432
      SS_DB_USER: snookers
      SS_DB_PASS: snookers
      SS_DB_DATABASE: snookers
    ports:
      - "28080:28080"
