version: '3.5'

services:
  duconCMS_database:
    image: mysql:5.7
    container_name: snookers_sells_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snookers_sells
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 53306:3306
    volumes:
      - snookers_sells_data:/var/lib/mysql

volumes:
  snookers_sells_data:
