version: "3"
services:
  db:
    image: postgres:14-alpine
    container_name: snookersbuddy-db
    environment:
      POSTGRES_USER: snookers
      POSTGRES_PASSWORD: snookers
    volumes:
      - snookersbuddy-db:/var/lib/postgresql/data
    ports:
      - "25432:5432" # Avoid conflict with other Postgres installations (e.g. system packaged).

volumes:
  snookersbuddy-db:
